### PR TITLE
Add automated CI builds

### PR DESCRIPTION
**Pull request by jbergler**
This adds two github actions
1. A build on every push that tries to build both windows + mac
2. A release action for new tags that builds and publishes binaries to a github release

Thanks for doing the leg work getting this setup, I hope this makes it easier to release/distribute

### CODE REVIEW

**Comment by jbergler** [comment]
The version number on this is me futzing around, but this is what the end result looks like after a tag get pushed
https://github.com/jbergler/cheekyavo/releases

**Comment by jbergler** [comment]
I'm not well versed with angular, so it's unclear to me if the changes to "ng build" in make and publish are sensible, but they seemed to be necessary to get the resulting binaries to actually load the app.

Reading the docs we might have to hook into the electron-forge 'prePackage' hook to have it do this without making it explicit in the npm script declaration.

**Review by cheekyavo — COMMENTED** [review]
Great work! 

Before I approve this, is there a size limit for storing artifacts in GitHub releases? I ran into a problem trying to check in the ZIP file before. https://github.com/cheekyavo/cheekyavo/releases

**Comment by jbergler** [comment]
No limits as far as I can tell.

**Comment by cheekyavo** [comment]
Hey mate, thank you so much for your PR, however, I've decided to re-write the whole things as a Google Chrome extension to make it easier to use. As a result, I dont think this CI effort is needed anymore, so I will close you PR. Thank you!

**Pull request closed without merging**
